230625/orderInfo.html 수정, payInfo.html, orderDone.html 추가
returnsss/furniture pull request #25
Opened 2023-06-25 10:39 UTC by returnsss

OrderInfo 테이블 key 변경
토스페이 결제 기능 추가
주문정보 입력한 뒤 결제 전 화면, 결제 한 뒤 주문 정보 출력하는 화면 추가

2023-06-25 10:59 UTC, hil00137 requested changes

2023-06-25 10:59 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/dtos/OrderStep.java
> +    OrderReceive("주문접수"),
ORDER_RECEIVE 와 같은 방식으로 해야함

2023-06-25 10:59 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +        for (OrderData orderData : orderDatas){
```java
List<OrderDataDto> orderDataDtoList = orderDatas.stream().map(orderData -> {

   // OrderDataDto 만드는 로직
}).collect(Collectors.toList())
```
위와 같이 jdk 8에서 나오는 Stream을 이용한 처리중 map을 이용한 데이터 변환 방식을 사용해보는걸로 변경해보기
https://thalals.tistory.com/321

2023-06-25 10:59 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +    public void updateOrderStepShippingProgress(String orderNum){
메소드 명은
orderStep무언가로 변경한다 라기보다는
단순하게 shippingProgress() 와 같은 메소드명을 쓰는 것이 서비스 관리 입장에서 좋아보임

"주문상태를배송프로세스로변경하기"
보다는
"배송진행"
같은 이름이 서비스의 메소드명으로서 더 좋아보인다는 말임.

2023-06-25 10:59 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +        orderInfo.setOrderStep(String.valueOf(OrderStep.ShippingProgress));
OrderInfo의  orderStep을 아래 문서를 보고 필드 형태 변경해보기
https://pamyferret.tistory.com/6

2023-06-25 10:59 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +        return orderProductName += " 외 " + (orderProductCnt - 1) + "건";
orderProductCnt  는 orderDataList.size() 로 대체 될수 있으며
orderProductName 은 orderDataList.stream().first() 와같은걸로 찾는것이 안전함.

혹은 orderDataList 의 size에 따라 message를 수정하는 식으로 해볼수 있을것 같음.


```java
if (orderDataList.isEmpty()) {
    // 주문이 없는것에 대한 Exception
}

String firstProductName = orderDataList.get(0).getProductName();

if (orderDataList.size() == 1) {
   return firstProductName;
}

return firstProductName  += " 외 " + (orderDataList.size() - 1) + "건";

```

2023-06-25 10:59 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +        log.info("paymentKey : " + paymentKey);
실제 데이터가 있는지 체크해보았는지?

2023-06-26 06:17 UTC, returnsss commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +        log.info("paymentKey : " + paymentKey);
로그 확인해서 체크 했어요

2023-06-26 06:17 UTC, returnsss commented
바로 머지하고 다른거 할게요

2023-06-26 06:17 UTC, merged