230626/주문완료시 세션의 orderNum 삭제, 내 정보의 주문 목록 출력
returnsss/furniture pull request #26
Opened 2023-06-26 09:16 UTC by returnsss

1. 주문한 뒤 로그아웃 하지 않고 바로 재주문할 경우 orderData와 orderInfo의 데이터가 지워지기 때문에 주문이 완료되면 세션의 orderNum을 삭제하도록 수정
2. 내 정보의 주문 목록 출력 OrderStep이 ORDER_FAIL인 것은 제외하고 출력하도록 제한
5개씩 출력, 페이징도 됨

2023-06-26 09:23 UTC, hil00137 requested changes

2023-06-26 09:23 UTC, hil00137 commented on src/main/resources/templates/mypage/orderList.html
> +        <div th:each="list, index : ${list}"
list로 받아서 해당 개별 아이템의 이름이 list인건 코딩시 혼란을 줄수 있음.
수정할것

비슷한 코딩을 했던게 저번 PR때 있었던걸로 보이므로 혹시 있나 다시 한번점검

2023-06-26 09:23 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/repository/OrderInfoRepositoryCustomImpl.java
> +        Long count = getCount(searchVal);
content를 뽑는데 쓰는 where 조건과
count를 뽑는 where조건이 다르므로 올바른 데이터가 나오지 않음

content 조건 (searchVal, ORDER_FAIL고려)
count 조건 (없음 -> 전체 조회)

2023-06-27 14:20 UTC, hil00137 requested changes

2023-06-27 14:20 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/repository/OrderInfoRepositoryCustomImpl.java
> +
해당 카운트는 ORDER_FAIL이 아닌 애들도 조건이 포함되어야함.

2023-06-28 06:53 UTC, returnsss commented
바로 머지할게요

2023-06-28 06:53 UTC, merged