230628/admin용 회원들 주문 내역 출력 화면, 자신의 주문 내역 출력부분 수정, 주문 성공시 상품 수량 주문한 갯수…
returnsss/furniture pull request #27
Opened 2023-06-28 16:16 UTC by returnsss

… 만큼 감소하게 수정

1. 관리자용 화면에서 회원들 주문내역 출력하는 화면 구현(5개씩 출력 되도록 페이징) 
발송하기 누르면 OrderStep 변경 되도록 적용 후 확인
2. 일반 회원기능인 주문 내역 출력부분이 자신의 주문내역이 출력되는게 아니라 모든 회원의 주문 내역이 출력 되던 부분을 자신의 주문 내역만 나오도록 수정 후 확인
3. 주문 성공시 상품의 남은 수량이 줄어들지 않았는데 줄어 들도록 수정 후 확인

2023-06-29 01:27 UTC, hil00137 requested changes

2023-06-29 01:27 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +                product.setProductsInStock(product.getProductsInStock() - orderData.getCnt());
재고는 결제가 완료되었을때가 아니라 주문이 완료되었을때 차감하는게 맞는것으로 보임.
혹은 몇개의 재고를 lock해놓는 방식
주문이 취소가 되었을때는 lock을 푸는 방식
주문이 성공하면 실제로 차감하고

위의 방식은 주문만해놓고 돈을 늦게 내면 물건을 못받는 상황도 나옴.

2023-06-29 01:27 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +                Product product = productRepository.findById(Long.valueOf(orderData.getProductId())).orElseThrow();
개인적으로는 productId를 한번에 모아서 조회한뒤에, Map으로 만들고, 업데이트하는 방식이 어떨까 싶음.
말했듯이 네트워크 비용. (물론 order할때 주문하는 상품의 갯수가 적어서 한번에 주문할수 있는 상품의 종류가 많지 않다면 위의 방식도 괜찮음)

2023-06-29 10:16 UTC, returnsss commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +        List<OrderData> orderDataList = orderDataRepository.findByOrderNumIn(orderNums);
findByOrderNumIn은 OrderDataRepository에 있는데 추가가 안된것으로 보인다는게 무슨 말인가요??

2023-06-29 10:17 UTC, returnsss commented on src/main/java/com/teamproject/furniture/order/repository/OrderInfoRepositoryCustomImpl.java
> +        String userId = UserUtil.getUserId();
private List<OrderInfoDto> getOrderInfoDtos(String searchVal, Pageable pageable) {
        BooleanBuilder whereClause = new BooleanBuilder();
        String userId = UserUtil.getUserId();

        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        boolean isAdmin = authentication.getAuthorities().stream()
                .anyMatch(authority -> authority.getAuthority().equals("ROLE_ADMIN"));

        if (searchVal != null && !searchVal.isEmpty()) {
            whereClause.and(orderInfo.orderNum.containsIgnoreCase(searchVal));
        }

        if (isAdmin) {
            whereClause.and(orderInfo.orderStep.eq(OrderStep.PAY_RECEIVE));
        } else {
            whereClause.and(orderInfo.orderStep.ne(OrderStep.ORDER_FAIL));
            whereClause.and(orderInfo.userId.eq(userId));
        }

        List<OrderInfoDto> content = queryFactory
                .select(new QOrderInfoDto(
                        orderInfo.orderNum,
                        orderInfo.userId,
                        orderInfo.orderName,
                        orderInfo.orderTel,
                        orderInfo.orderEmail,
                        orderInfo.receiveName,
                        orderInfo.receiveTel,
                        orderInfo.receiveAddress,
                        orderInfo.orderStep,
                        orderInfo.payAmount,
                        orderInfo.orderDate,
                        orderInfo.payDate))
                .from(orderInfo)
                .where(whereClause)
                .orderBy(orderInfo.orderNum.desc())
                .offset(pageable.getOffset())   // 페이지 번호
                .limit(pageable.getPageSize())  // 페이지 사이즈
                .fetch();

        return content;
    }
이렇게 합쳐봤는데 상단 공용 nav에서 보는 주문 내역과 관리자용 nav의 주문 관리가 하는 기능이 다른데 관리자로 로그인 되어있으면 둘 다 관리자용 기능밖에 동작하지 않아서 원래 했던대로 되돌렸어요

2023-06-29 10:17 UTC, returnsss commented on src/main/java/com/teamproject/furniture/order/service/OrderService.java
> +                product.setProductsInStock(product.getProductsInStock() - orderData.getCnt());
isSuccess일때 실행되는 건데 isSuccess가 결제가 다 완료 된 거 아닌가요?
원래 기존 프로젝트가 관리자용 주문관리에서 발송하기 누르면 orderStep이 shippingprogress로 바뀌고 cnt가 줄어드는 식이었는데 어제 만들면서 생각해보니까 돈 다 지불하면 바로 cnt 감소하는게 맞는거 같아서 이렇게 바꾼거였는데 발송하기 누르면 product의 남은 수량이 감소하는 걸로 다시 바꿀까요?

2023-06-29 10:21 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/repository/OrderInfoRepositoryCustomImpl.java
> +        String userId = UserUtil.getUserId();
isAdmin을 하라는건 사용자가 admin인지 체크하는게 아니라 해당 쿼리를 호출하는쪽에서 admin 쿼리로 호출할꺼냐 admin이 아닌 쿼리로 호출할껀지만 구분했으면 됨.

2023-06-29 10:27 UTC, hil00137 requested changes
ㅌ

2023-06-29 13:42 UTC, hil00137 requested changes

2023-06-29 13:42 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/admin/controller/AdminViewController.java
> +        Page<OrderInfoDto> results = orderService.selectOrderList(searchVal, pageable, isAdmin);
어짜피 이쪽 API를 사용할수 있는건 admin이기 때문에 고정값 true를 넘기면 됨.

2023-06-29 13:42 UTC, hil00137 commented on src/main/java/com/teamproject/furniture/order/controller/OrderViewController.java
> +        Page<OrderInfoDto> results = orderService.selectOrderList(searchVal, pageable, isAdmin);
그냥 false를 넘기면됨 isAdmin 이란 변수 안만들고

2023-06-30 07:57 UTC, returnsss commented
바로 머지하고 lock_cnt부분 해볼게요

2023-06-30 07:57 UTC, merged